name: TrafficApp
on:
  push:
    branches:
      -master

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Chechout code
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test -- --coverage
